- app/controllers/admin/genres_controller.rb
- app/models/genre.rb
- app/models/item.rb
- app/views/admin/genres/edit.html.erb
- app/views/admin/genres/index.html.erb
- app/views/admin/sessions/new.html.erb
- app/views/public/registrations/new.html.erb
- app/views/public/sessions/new.html.erb
genre [farst-pull-request]
ジャンルの追加・一覧・編集
> kotty[genre]

- app/controllers/admin/customers_controller.rb
- app/models/customer.rb
- app/views/admin/customers/edit.html.erb
- app/views/admin/customers/index.html.erb
- app/views/admin/customers/show.html.erb
- app/views/public/homes/top.html.erb
- config/locales/ja.yml
- config/webpack/environment.js
Description　file
views/admin/customer/index　=>　add_page
views/admin/customer/show　=>　add_page
views/admin/customer/edit　=>　add_page
controller/admin/customers_controller　=>　add_action
models/customer　=>　add_validates
> Create admin customer info

- app/controllers/public/cart_items_controller.rb
- app/models/cart_item.rb
- app/views/public/cart_items/index.html.erb
public:cart_item
・controller
・view
> Public cart item

- app/controllers/public/cart_items_controller.rb
- app/controllers/public/items_controller.rb
- app/models/cart_item.rb
- app/models/customer.rb
- app/views/public/cart_items/index.html.erb
- app/views/public/items/index.html.erb
- app/views/public/items/show.html.erb
- config/routes.rb
[Add]public:items,cart_items
items
・controller(index,show)
・view(index,show)
cart_items
・model(relation)
・controller(index,create,update,destroy,destroy_all)
・view(index)
other
・Route:destroy_all [fix]
Viewは後で再調整します。
> Add customer item cart item

- app/models/customer.rb
- app/models/destination.rb
- app/models/order.rb
- app/models/order_detail.rb
- config/locales/devise.ja.yml
> [fix]flash

- app/controllers/admin/order_details_controller.rb
- app/controllers/admin/orders_controller.rb
- app/controllers/public/orders_controller.rb
- app/views/admin/homes/top.html.erb
- app/views/admin/orders/show.html.erb
- app/views/layouts/application.html.erb
- app/views/public/orders/confirm.html.erb
> order_detail

- app/controllers/public/cart_items_controller.rb
- app/views/public/cart_items/index.html.erb
> Fix cart item

- app/views/admin/customers/index.html.erb
> admin_cutomer_table

- app/controllers/admin/customers_controller.rb
- app/views/admin/customers/orders.html.erb
- app/views/admin/customers/show.html.erb
- config/routes.rb
> Admin customer order

- app/controllers/searchs_controller.rb
- app/models/genre.rb
- app/views/layouts/_search.html.erb
- app/views/public/items/_left_menu.html.erb
- app/views/searchs/search.html.erb
> Search genre

- app/views/admin/genres/edit.html.erb
- app/views/admin/genres/index.html.erb
- app/views/admin/sessions/new.html.erb
- app/views/public/orders/new.html.erb
- app/views/public/registrations/new.html.erb
- app/views/public/sessions/new.html.erb
> genre,admin/sing_in,public(view)

- app/controllers/public/cart_items_controller.rb
- app/models/cart_item.rb
- app/views/public/cart_items/index.html.erb
> Cart item fix

- app/controllers/application_controller.rb
- app/controllers/public/registrations_controller.rb
- app/views/public/registrations/new.html.erb
> 新規登録後の遷移先変更

- app/controllers/admin/orders_controller.rb
- app/views/admin/homes/top.html.erb
- app/views/admin/orders/show.html.erb
view_homes_top　配送先名を購入者に変更
View_order_show 姓名を逆に変更、合計金額の表示を変更
> viewのorder_show.home_topを編集

- app/views/admin/customers/index.html.erb
> admin_customer

- app/views/admin/orders/show.html.erb
> order_show 編集

- app/views/admin/items/index.html.erb
- app/views/public/cart_items/index.html.erb
- app/views/public/customers/edit.html.erb
- app/views/public/customers/show.html.erb
- app/views/public/customers/soft_delete.html.erb
> change-color5

- app/views/admin/sessions/new.html.erb
- app/views/public/destinations/edit.html.erb
- app/views/public/destinations/index.html.erb
- app/views/public/registrations/new.html.erb
- app/views/public/sessions/new.html.erb
> 配送先・新規登録view

- app/views/layouts/_search.html.erb
- app/views/public/cart_items/index.html.erb
- app/views/public/customers/edit.html.erb
- app/views/public/customers/show.html.erb
- app/views/public/items/index.html.erb
- app/views/public/orders/confirm.html.erb
- app/views/public/orders/new.html.erb
- app/views/searchs/search.html.erb
> change_color6

- app/views/admin/customers/show.html.erb
- app/views/public/cart_items/index.html.erb
> 会員詳細(admin)

- app/views/public/orders/complete.html.erb
- app/views/public/orders/confirm.html.erb
> change_color7

- app/views/public/cart_items/index.html.erb
- app/views/public/destinations/edit.html.erb
- app/views/public/destinations/index.html.erb
- app/views/public/homes/top.html.erb
- app/views/public/items/_index.html.erb
- app/views/public/items/index.html.erb
- app/views/public/items/show.html.erb
- app/views/searchs/search.html.erb
> change_view
